version: '3.7'

services:
  redis:
    image: redis:6.2.4-alpine3.13
    hostname: redis
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    container_name: myredis
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf

  prometheus:
    image: prom/prometheus:v2.27.1
    hostname: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    container_name: myprometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'

  fluentd-aggregator:
    image: grafana/fluent-bit-plugin-loki:2.3.0-amd64
    hostname: fluentd-aggregator
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - loki

  loki:
    image: grafana/loki:2.3.0
    hostname: loki
    ports:
      - "3100:3100"
    container_name: myloki
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.1.5
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel 1.6.2"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: mygrafana
    networks:
      - grafana
      - loki

  concourse-db:
    image: postgres:9.6.22
    hostname: concourse-db
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass

  concourse:
    image: concourse/concourse:7.3.2
    hostname: concourse
    command: quickstart
    privileged: true
    depends_on: [ concourse-db ]
    ports: [ "8080:8080" ]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: tutorial
      CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"

networks:
  grafana:
    name: grafana
    driver: bridge
  loki:
    name: loki
    driver: bridge






