platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "11"

inputs:
- name: source-code

run:
  path: D:\intelliJDataSource\spring-boot-RESTful/ci/tasks/package.sh