platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "11"

inputs:
- name: source-code

run:
  path: "mvn"
  args: ["-f", "D:\intelliJDataSource\spring-boot-RESTful\pom.xml", "test"]