server:
  port: 8080

spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:oauth;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop