version: '3.7'

volumes:
  prometheus_data: { }
  grafana_data: { }

services:
  redis:
    image: redis:6.2.4-alpine3.13
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    container_name: myredis
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf

  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    container_name: myprometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'

  promtail:
    image: grafana/promtail:k51-8618abc
    volumes:
      - ./promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
      - ./log/log.log:/var/log/log.log
    command: -config.file=/etc/promtail/docker-config.yaml
    container_name: mypromtail

  loki:
    image: grafana/loki:k51-8618abc
    ports:
      - "3100:3100"
    container_name: myloki

  grafana:
    image: grafana/grafana:8.0.1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: mygrafana
    restart: always

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: myjenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ../../../jenkins:/var/jenkins_home # 主機 jenkins庫(自訂)
      - ../../apache-maven-3.6.3/mavenRepository:/root/.m2 # 主機 Maven 儲存庫至容器內(自訂)







