version: '3.7'

volumes:
  prometheus_data: { }
  grafana_data: { }

services:
  redis:
    image: redis
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    container_name: myredis
    ports:
      - '6379:6379'
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    container_name: myprometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: mygrafana
    restart: always

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    container_name: myloki
    
  promtail:
    image: grafana/promtail
    volumes:
      - ./log:/var/log
    command: -config.file=/etc/promtail/config.yml
    container_name: mypromtail


