resources:
  - name: concourse-docs-git
    type: git
    icon: github
    source:
      uri: https://github.com/Aryido/spring-boot-RESTful.git

jobs:
  - name: job
    public: true
    plan:
      - get: concourse-docs-git
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: concourse-docs-git
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
            args: ["-la","./concourse-docs-git"]
      - task: mvn-test
        config:
          inputs:
            - name: concourse-docs-git
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: maven }
          run:
            path: mvn
            args: ["-f","./concourse-docs-git/pom.xml","test"]