resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/Aryido/spring-boot-RESTful.git
      branch: main

jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - task: package
    privileged: true
    file: D:\intelliJDataSource\spring-boot-RESTful/ci/tasks/package.yml